export enum ACTION_TYPE {
    //          ---         ACTION TYPES FOR TODOLIST           ---         

    ADD_NEW_TODOLIST = "ADD-NEW-TODOLIST",
    REMOVE_TODOLIST = "REMOVE-TODOLIST",
    CHANGE_TITLE_TODOLIST = "CHANGE-TITLE-TODOLIST",
    CHANGE_FILTER_TODOLIST = "CHANGE-FILTER-TODOLIST",
    SET_TODOLISTS = "SET_TODOLISTS",

    //          ---         ACTION TYPES FOR TODOLIST           ---

    ADD_NEW_TASK = "ADD-NEW-TASK",
    REMOVE_TASK = "REMOVE-TASK",
    CHANGE_TASK_TITLE = "CHANGE-TASK-TITLE",
    CHANGE_TASK_STATUS = "CHANGE-TASK-STATUS",
    SET_TASKS = "SET_TASKS",
}